name: check

on:
  push:
  pull_request:
  schedule:
    - cron: '10 16 * * FRI'

jobs:
  check-duplication:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content_newer'

  analyze:
    needs: check-duplication
    if: ${{ needs.check-duplication.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [ stable, beta, dev, master ]
    steps:
      - uses: CCXXXI/flutter-action@main
        with:
          channel: ${{ matrix.channel }}

      - run: flutter analyze

  coverage:
    needs: check-duplication
    if: ${{ needs.check-duplication.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [ stable, beta, dev, master ]
    steps:
      - uses: CCXXXI/flutter-action@main
        with:
          channel: ${{ matrix.channel }}

      - run: flutter test --coverage
      - uses: codecov/codecov-action@v2

  dependency_validator:
    needs: check-duplication
    if: ${{ needs.check-duplication.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [ stable, beta, dev, master ]
    steps:
      - uses: CCXXXI/flutter-action@main
        with:
          channel: ${{ matrix.channel }}

      - run: flutter pub run dependency_validator
